### ISSUE TITLE
missing configurable option csiPluginName

### ISSUE THREAD

**Issue by wesselvdv** [eddycharly/terraform-provider-kops#213]
I am missing the option to configure the following property:

```yaml
  cloudConfig:
    openstack:
      blockStorage:
        csiPluginImage: docker.io/k8scloudprovider/cinder-csi-plugin:v1.20.3
```

Without this option, I can't deploy kops.
