### ISSUE TITLE
error running tasks: deadline exceeded executing task FloatingIP/fip-api.dev.k8s.local. Example error: Failed to create floating IP: CreateL3FloatingIP: create L3 floating IP failed: Resource not found

### ISSUE THREAD

**Issue by wesselvdv** [eddycharly/terraform-provider-kops#251]
I am running into an issue where kops is unable to execute a task related to assigning/creating a floating ip. I have also created an issue at the kops repository [(here)](https://github.com/kubernetes/kops/issues/11889) because I think this task is also failing on the cli but seems to resolve itself regardless of the error. (floating ip is created/assigned) It seems this provider is more strict, and is really expecting the task to complete.

Error:

```
error running tasks: deadline exceeded executing task FloatingIP/fip-api.dev.k8s.local. Example error: Failed to create floating IP: CreateL3FloatingIP: create L3 floating IP failed: Resource not found
```

I can guarantee that openstack credentials are working, as I am seeing other resources being created.

**Comment by eddycharly** [comment]
Hey @wesselvdv at least the credentials issue was fixed.

Do you have more details ? Does the cluster finishes by being created (maybe after applying the tf code multiple times) ?

The lifecycle should apply the cluster spec and create the necessary cloud resources.
What happens if you skip validation in the lifecyle ?

I guess the floating ip is coming from this part of the spec:
```yaml
  cloudConfig:
    openstack:
      blockStorage:
        bs-version: v3
        csiPluginImage: docker.io/k8scloudprovider/cinder-csi-plugin:v1.20.3
        ignore-volume-az: true
        override-volume-az: nova
      loadbalancer:
        floatingNetwork: public
        floatingNetworkID: 586f0e36-993f-40f0-9ebc-e8329ec06d22
        method: ROUND_ROBIN
        provider: haproxy
        useOctavia: false
      monitor:
        delay: 1m
        maxRetries: 3
        timeout: 30s
      router:
        externalNetwork: public
```

Are there some options that can be changed to allow more time for the floating ip to show up (` deadline exceeded executing task` looks like a timeout issue) ?
