### ISSUE TITLE
Import error: kops cluster with external policies

### ISSUE THREAD

**Issue by rmgpinto** [eddycharly/terraform-provider-kops#282]
I'm trying to import an existing cluster with `external_policies` defined, but I get:

```
provider.terraform-provider-kops_v1.20.0-beta.2: 2021/07/12 21:57:24 [ERR] Error writing fields: external_policies.node.1: '': source data must be an array or slice, got string: timestamp=2021-07-12T21:57:24.554+0100
```

I have something similar to this:
```
spec:
  externalPolicies:
    node:
    - arn:aws:iam::123456789000:policy/test-policy-1
    - arn:aws:iam::123456789000:policy/test-policy-2
 ```
