### ISSUE TITLE
Golang zero values are not set in kops cluster config

### ISSUE THREAD

**Issue by peter-svensson** [eddycharly/terraform-provider-kops#330]
The creation of cluster (and perhaps other ) configs are not handling golang zero values. 
The zero value for a `bool` is `false` and the parameters set in the terraform files with `false` are not propagated to the kops configuration.

For example:
```tf
  metrics_server {
    enabled  = true
    insecure = true
  }
```
Renders correctly to:
```yaml
  metricsServer:                                                                                                  
    enabled: true
    insecure: true
```

However:
```tf
  metrics_server {
    enabled  = true
    insecure = false
  }
```
Renders to:
```yaml
  metricsServer:                                                                                                  
    enabled: true
```

This happens for all settings that I've tested, which more or less breaks every cluster.
