### ISSUE TITLE
kube-proxy & kube-controller-manager cluster-cidr is incorrectly populated

### ISSUE THREAD

**Issue by dkulchinsky** [eddycharly/terraform-provider-kops#386]
Howdy 👋🏼 me again 😄 

We've hit another strange issue, for some reason the `ClusterCIDR` value for `kubeProxy` and `kubeControllerManager` is being set to `spec.serviceClusterIPRange` instead of `spec.poDCIDR`

for example, if the cluster sperc has:
```yaml
metadata:
  name: sbx-awsuse2.k8s.local
spec:
  podCIDR: 172.18.0.0/17
  serviceClusterIPRange: 172.18.128.0/17
```

`kubeProxy` & `kubeControllerManager` ends with:
```yaml
  kubeControllerManager:
    clusterCIDR: 172.18.128.0/17
```

```yaml
  kubeProxy:
    clusterCIDR: 172.18.128.0/17
```

which is incorrect, since the `clusterCIDR` should be the `podCIDR` and not `serviceClusterIPRange`

we worked around it by specifying the value of `clusterCIDR` explicitly in the `kops_cluster` resource:
```
  kube_proxy {
    enabled      = true
    proxy_mode   = var.kube_proxy_mode
    cluster_cidr = local.pod_cidr
  }

  kube_controller_manager {
    cluster_cidr = local.pod_cidr
  }
```

let me know if you need any additional information.
