### ISSUE TITLE
Booting from a volume in OpenStack 

### ISSUE THREAD

**Issue by mattjudge** [eddycharly/terraform-provider-kops#578]
It's not clear how to provide the metadata annotations to instance groups required to [enable booting from a volume in OpenStack](https://kops.sigs.k8s.io/tutorial/working-with-instancegroups/#booting-from-a-volume-in-openstack).

It's necessary to provide the following annotations:

- `openstack.kops.io/osVolumeBoot`
- `openstack.kops.io/osVolumeSize`

A YAML example:
```
# Example for nodes
apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  labels:
    kops.k8s.io/cluster: k8s.dev.local
  name: nodes
  annotations:
    openstack.kops.io/osVolumeBoot: enabled
    openstack.kops.io/osVolumeSize: "15" # In gigabytes
spec:
  detailedInstanceMonitoring: true
  machineType: t2.medium
  maxSize: 2
  minSize: 2
  role: Node
```

I can't see a way to add that to the terraform definition, and searching the codebase hasn't returned much - apologies if I've missed it though.
